### ISSUE TITLE
Does this project have an active maintainer?

### ISSUE THREAD

**Issue by mariusgrigaitis** [atomita/fluent-plugin-aws-elasticsearch-service#29]
I see that there are no changes merged for like half a year. I would like to use this package but it seems that it does not have an active maintainer?

**Comment by aibou** [comment]
How about using the Amazon Kinesis Firehose instead?
I have stopped using this plugin and started using it and https://github.com/awslabs/aws-fluent-plugin-kinesis because I had trouble as #25 and it seems there is no future to resolve it.

However, the Firehose outputs to the ES domains only same region, then this idea can apply in us-east-1, us-west-2, eu-west-1 regions :(
# Although I always use ap-northeast-1, I created ES domains in us-west-2.

**Comment by mpas** [comment]
I am also running into issues using this plugin. Any good recommendation as an alternative? I looked at putting the logs in S3 and stream to ES. But this is a very costly approach.

**Comment by repeatedly** [comment]
There are 2 approaches:

- someone becomes new maintainer if @atomita is ok
-- option is fluent-plugin-nursery for temporal place
- fork plugin (I don't want to do)

**Comment by dwoo4dwoo** [comment]
@repeatedly - what would you think of extending uken/fluent-plugin-elasticsearch to support Amazon signing?  Amazon signing seems to be the biggest (only?) feature lacking in uken/fluent-plugin-elasticsearch?

**Comment by yissachar** [comment]
This plugin is small enough that rolling functionality into fluent-plugin-elasticsearch makes a lot of sense. On the other hand that plugin is not well-maintained either these days.

**Comment by repeatedly** [comment]
I'm not sure because I'm not a maintainer of elasticsearch plugin.
If the maintainer and contributor is okay, it is good idea.

**Comment by dwoo4dwoo** [comment]
> On the other hand that plugin is not well-maintained either these days.

@yissachar - yeah, I thought this was being resolved in https://github.com/uken/fluent-plugin-elasticsearch/pull/240, in particular that @repeatedly was being given access.  I just re-read that PR now and it still seems unresolved.  This is a real bummer because for many people, myself included, Fluentd loses a lot of value without a good well maintained Elasticsearch plugin.

**Comment by Nossnevs** [comment]
@cosmo0920 are you interested to merge this plugins functionality in to uken/fluent-plugin-elasticsearch ?@atomita are you good with this and let this plugin die?

**Comment by cosmo0920** [comment]
No. I'm not familiar with AWS Elasticsearch Service.

**Comment by repeatedly** [comment]
If someone wants to merge this feature into ES plugin, new active maintainer for AWS ES parts is needed.
But I think forking this project is better. ES can focus on ES feature, not transport.

**Comment by cosmo0920** [comment]
I'd became an active maintainer. (But still @atomita wants to publish this plugin by his own.)
So, we can close this issue.
