### ISSUE TITLE
Depends on aws sdk v3

### ISSUE THREAD

**Issue by cosmo0920** [atomita/fluent-plugin-aws-elasticsearch-service#33]
Recently, aws sdk gem v3 is released.
We should use aws sdk v3 instead of v2.

**Comment by lobeck** [comment]
This is a requirement for td-agent version v3.1.0 as this comes with aws sdk v3 and adding v2 causes a conflict.

`/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate aws-sdk-resources-2.11.38, because aws-sdk-core-3.11.0 conflicts with aws-sdk-core (= 2.11.38) (Gem::ConflictError)`

**Comment by krrrr38** [comment]
When I do`yum install -y td-agent`, install `aws-sdk-core-3.11.0` into `/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/`.
After install `sudo /usr/sbin/td-agent-gem install fluent-plugin-aws-elasticsearch-service`, install `aws-sdk-core-2.11.39`. Then `Gem::ConflictError` happen.
Is there any update? @cosmo0920

**Comment by cosmo0920** [comment]
> Is there any update? @cosmo0920

Could you take a look, @atomita ?

**Comment by lobeck** [comment]
I already have a working patch, maybe i can push a branch later with more details.

**Comment by krrrr38** [comment]
`1.1.0-alpha` is works in my env, thanks 👏
